class Autogenerated {
  Base? base;

  Autogenerated({this.base});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    base = json['base'] != null ? Base.fromJson(json['base']) : null;
  }
}

class Base {
  int? code;
  String? msg;

  Base({this.code, this.msg});

  Base.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    msg = json['msg'];
  }

  Map<String, dynamic> toJson() {
    return {
      'code': code,
      'msg': msg,
    };
  }
}
